spring:
  datasource:
    url: jdbc:h2:mem:maindb

  h2:
    console:
      enabled: false

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

  sql:
    init:
      mode: never

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: validate

    properties:
      hibernate:
        format_sql: true

    show-sql: true
    open-in-view: false

  data:
    rest:
      base-path: /hateoas

logging:
  level:
    ROOT: INFO
  file:
    name: "log.txt"

management:
  endpoint:
    health:
      show-details: always
    logfile:
      enabled: true
  health:
    defaults:
      enabled: true
  endpoints:
    web:
      exposure:
        include: metrics, health, logfile